version: "3.9"

services:
  dev: 
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      PORT: 8000
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_ORGANIZATION_ID: ${OPENAI_ORGANIZATION_ID}
    ports:
      - 8000:8000
    volumes:
      - ./main.go:/app/main.go

  release:
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      PORT: 80
    ports:
      - 80:80